# config/packages/twig.yaml
twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    # default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/img/icons': img

    globals:
        app_environement: '%env(APP_ENV)%'
        stripe_public_key_test: '%env(STRIPE_PUBLIC_KEY_TEST)%'
        stripe_public_key_live: '%env(STRIPE_PUBLIC_KEY_LIVE)%'
        
when@test:
    twig:
        strict_variables: true
